const express = require("express");
const router = express.Router();
const { createReportController, getUserReportsController, getSingleReportController } = require("../controllers/interview.controller");
const authMiddleware = require("../middlewares/auth.middleware");

/**
 * @route POST /api/reports/generate
 * @desc Generate and save a new interview report on the basis of user self description, resume pdf and job description
 * @access Private
 */
router.post("/generate", authMiddleware.authenticateToken, createReportController);

/**
 * @route GET /api/reports
 * @desc Get all reports generated by the logged in user
 * @access Private
 */
router.get("/", authMiddleware.authenticateToken, getUserReportsController);

/**
 * @route GET /api/reports/:id
 * @desc Get a specific report details
 * @access Private
 */
router.get("/:id", authMiddleware.authenticateToken, getSingleReportController);

module.exports = router;
